# Reload config file
bind r source-file ~/.config/tmux/.tmux.conf

# Clock mode
setw -g clock-mode-colour '#ff5c5c'
setw -g clock-mode-style 24

# Copy mode
setw -g mode-style 'bg=#1e1e2e fg=#cdd6f4 bold'

# Enable vi mode for scrollback history and status keys
setw -g mode-keys vi
set -g status-keys vi

# Remap copying behavior to match Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Pane Vim bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Pane Resize Vim bindings
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Window & Pane number start at 1
setw -g pane-base-index 1
set -g base-index 1

# Panes
set -g pane-border-style 'fg=#313244'
set -g pane-active-border-style 'fg=#89b4fa'

# Status bar
set -g status-position top
set -g status-justify left
set -g status-style 'bg=#1e1e2e fg=#cdd6f4'

set -g status-left-style 'fg=#a6e3a1 bg=#1e1e2e'
set -g status-left ' [#S] '
set -g status-left-length 10

set -g status-right-style 'fg=#89b4fa bg=#1e1e2e'
set -g status-right ' [%m-%d-%Y | %H:%M] '
set -g status-right-length 50

set -g window-status-current-style 'fg=#11111b bold bg=#89b4fa'
set -g window-status-current-format ' #I:#W#F '

set -g window-status-style 'fg=#cdd6f4 bg=#313244'
set -g window-status-format ' #I:#[fg=white]#W#F '

set -g window-status-bell-style 'fg=#cdd6f4 bg=#313244'

# Messages
set -g message-style 'fg=#cdd6f4 bg=#313244'
